# Generated by Django 2.1.7 on 2019-03-06 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20190306_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assigne', to=settings.AUTH_USER_MODEL, verbose_name='task_assigne'),
        ),
    ]
