# Generated by Django 2.1.7 on 2019-02-27 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20190227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_users', to=settings.AUTH_USER_MODEL, verbose_name='team_users'),
        ),
    ]
