# Generated by Django 2.1.7 on 2019-03-18 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0006_auto_20190307_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_assigne', to=settings.AUTH_USER_MODEL, verbose_name='task_assigne'),
        ),
    ]
