# Generated by Django 2.1.7 on 2019-03-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20190305_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
    ]
